### ISSUE TITLE
Support stand-alone packages without project-specific files (package.json at root)

### ISSUE THREAD

**Issue by MostHated** [reeseschultz/ubump#19]
Hey there,
    I have successfully used ubump a number of times and it is a great tool so thank you much for sharing it. My prior packages had been full Unity projects which had an embedded package. I had created a small package of extension methods I use often and wanted to make it a package that I could just then just use as a dependency of other projects but it is just a standalone package with no assets folder or anything and just the folders and project manifest in the repo root. Not thinking much about it, I attempted to run ubump against it and received back an error because it was not actually a Unity project.

This leads to my actual question, is there a way to still bump and tag a standalone package with ubump, or is it required to be a full-on Unity project first in order to accomplish bumping and tagging? If it is not currently possible, I would like to request that perhaps this could be considered sometime in the future, if possible.

Thanks,
-MH

**Comment by reeseschultz** [comment]
Thanks, glad you like it.

Presently, there's no way to do what you're requesting with ubump.

Do you know if there's an official standard for Unity packages that aren't technically in a project, or if this is a common practice?

As to how ubump uses the project, it reads/writes `ProjectSettings.asset`, a yaml file, and `ProjectVersion.txt`, both of which live in a directory called `ProjectSettings/`. It also looks at `Packages/manifest.json` (the project manifest), comparing it against a `package.json` (package manifest) to see if the package dependency versions need to be synchronized (fast-forwarded) with that of the project.

So really to support what you're asking, it would really just be a matter of doing a check and cutting out much of the complexity that ubump currently defaults to. Do you have a sample package I can fork for testing purposes, if I were to implement this?

**Comment by MostHated** [comment]
I would say it is anywhere from fairly to decently common. Unity supports importing packages in this manner, and even have a few published like this, themselves if I am not mistaken. 

Here was the repo I was attempting to bump, which should be perfectly fine for testing out.
https://github.com/instance-id/Extensions

**Comment by reeseschultz** [comment]
All right, thanks for providing those examples. I'll dust off ubump and have it support this type of package soon.

**Comment by MostHated** [comment]
Awesome, I definitely appreciate it. 👍

**Comment by reeseschultz** [comment]
You're welcome!

**Comment by reeseschultz** [comment]
All right, [version 0.4.4 of ubump](https://www.npmjs.com/package/ubump) should do exactly what you need now. If this doesn't work, let me know. I tested my changes against a fork of your stand-alone package repository.

**Comment by MostHated** [comment]
This is great news, I will give it a try here shortly and report back.

**Comment by MostHated** [comment]
I was finally able to give it a go and it seems to work well. Thanks again, I definitely appreciate it. 👍
